import type { STableColumnsType } from '@shene/table'
import { ref } from 'vue'

export type DataType = { [key: string]: string }

export const allColumns: STableColumnsType<DataType> = [
  {
    title: 'Target Pest',
    dataIndex: 'Target Pest',
    key: 'Target Pest',
    width: 200,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Pest Taxonomy ID',
    dataIndex: 'Pest Taxonomy ID',
    key: 'Pest Taxonomy ID',
    width: 250,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Target Pest Order',
    dataIndex: 'Target Pest Order',
    key: 'Target Pest Order',
    width: 250,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Pest Developmental Stage',
    dataIndex: 'Pest Developmental Stage',
    key: 'Pest Developmental Stage',
    width: 200,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'RNA Length (nt)',
    dataIndex: 'RNA Length (nt)',
    key: 'RNA Length (nt)',
    width: 140,
    ellipsis: false,
    resizable: true,
  },
  {
    title: 'RNA Sequence',
    dataIndex: 'RNA Sequence',
    key: 'RNA Sequence',
    width: 250,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'DNA length（bp）',
    dataIndex: 'DNA length（bp）',
    key: 'DNA length（bp）',
    width: 140,
    ellipsis: false,
    resizable: true,
  },
  {
    title: 'DNA Sequence',
    dataIndex: 'DNA Sequence',
    key: 'DNA Sequence',
    width: 250,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'RNA Type',
    dataIndex: 'RNA Type',
    key: 'RNA Type',
    width: 120,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'RNA Production Method',
    dataIndex: 'RNA Production Method',
    key: 'RNA Production Method',
    width: 200,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Target Gene Name',
    dataIndex: 'Target Gene Name',
    key: 'Target Gene Name',
    width: 180,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Gene Function',
    dataIndex: 'Gene Function',
    key: 'Gene Function',
    width: 200,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Gene ID',
    dataIndex: 'Gene ID',
    key: 'Gene ID',
    width: 120,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Mechanism of Pesticide/Biochemical Process',
    dataIndex: 'Mechanism of Pesticide/Biochemical Process',
    key: 'Mechanism of Pesticide/Biochemical Process',
    width: 250,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Application methods',
    dataIndex: 'Application methods',
    key: 'Application methods',
    width: 250,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Optimal Concentration',
    dataIndex: 'Optimal Concentration',
    key: 'Optimal Concentration',
    width: 160,
    ellipsis: true,
    resizable: true,
  },
  { title: 'LC50', dataIndex: 'LC50', key: 'LC50', width: 100, ellipsis: false, resizable: true },
  {
    title: 'Time to Onset',
    dataIndex: 'Time to Onset',
    key: 'Time to Onset',
    width: 140,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Duration of Efficacy',
    dataIndex: 'Duration of Efficacy',
    key: 'Duration of Efficacy',
    width: 160,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Stability（Chemical Stability、Environmental Stability、Half-Life）',
    dataIndex: 'Stability（Chemical Stability、Environmental Stability、Half-Life）',
    key: 'Stability（Chemical Stability、Environmental Stability、Half-Life）',
    width: 300,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Effect',
    dataIndex: 'Effect',
    key: 'Effect',
    width: 120,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Efficiency（Low：＜40%；Medium：40%-80%；High：＞80%）',
    dataIndex: 'Efficiency（Low：＜40%；Medium：40%-80%；High：＞80%）',
    key: 'Efficiency（Low：＜40%；Medium：40%-80%；High：＞80%）',
    width: 300,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Efficiency',
    dataIndex: 'Efficiency',
    key: 'Efficiency',
    width: 260,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Reference PMID',
    dataIndex: 'Reference PMID',
    key: 'Reference PMID',
    width: 150,
    ellipsis: true,
    resizable: true,
  },
  {
    title: 'Notes（Supplementary Information）',
    dataIndex: 'Notes（Supplementary Information）',
    key: 'Notes（Supplementary Information）',
    width: 300,
    ellipsis: true,
    resizable: true,
  },
]

export const selectedColumns = ref<string[]>([
  'Target Pest',
  'Target Pest Order',
  'Target Gene Name',
  'Application methods',
  'Effect',
  'Reference PMID',
])
